version: "3.4"

services:
  db:
    container_name: challengebox-backend-mariadb_dev
    environment:
      MYSQL_DATABASE: "challengeboxdb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  wildfly:
    container_name: challengebox-backend-wildfly_dev
    build:
      context: ..
      dockerfile: docker/components/runtime/Dockerfile
    volumes:
      - ../target/deployments:/opt/jboss/wildfly/standalone/deployments/
    ports:
      - "8080:8080"
      - "9990:9990"
    command: bash -c "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -c standalone-custom.xml"